var client = new RestClient("https://api.edenai.run/v1/pretrained/vision/ocr");
client.Timeout = -1;
var request = new RestRequest(Method.POST);
request.AddHeader("Authorization", "Bearer your_api_key");
request.AddParameter("providers", "[\'google\', \'microsoft\', \'aws\', \'ocrspace\']");
request.AddFile("files", "/Downloads/example.mp3");
request.AddParameter("language", "en-US");
request.AddParameter("text_reference", "'Hello world'");
IRestResponse response = client.Execute(request);
Console.WriteLine(response.Content);
