var client = new RestClient("https://api.edenai.run/v1/pretrained/text/language_detection");
client.Timeout = -1;
var request = new RestRequest(Method.POST);
request.AddHeader("Authorization", "Bearer your_api_key");
request.AlwaysMultipartFormData = true;
request.AddParameter("providers", "[\'ibm\', \'microsoft\', \'aws\', \'google_cloud\']");
request.AddParameter("text", "\'I am angry today\'");
request.AddParameter("language", "en-US");
IRestResponse response = client.Execute(request);
Console.WriteLine(response.Content);
